package madres.backend.auth

import org.jdbi.v3.core.Jdbi
import java.util.UUID

class AuthRepository(
    private val jdbi: Jdbi,
) {

    private val findUserByEmailSql = """
        SELECT id, email, password_hash
        FROM madres.users
        WHERE LOWER(email) = :email
        LIMIT 1
    """.trimIndent()

    private val startNewSessionSql = """
        INSERT INTO madres.sessions (user_id, expires_ts)
        VALUES (:userId, now() + interval '1 hour')
        RETURNING id;
    """.trimIndent()

    private val getSessionUserSql = """
        SELECT u.id AS user_id, u.email
        FROM madres.sessions s
        JOIN madres.users u ON u.id = s.user_id
        WHERE s.id = :sessionId
          AND s.expires_ts > now()
        LIMIT 1
    """.trimIndent()

    private val deleteSessionSql = """
        DELETE FROM madres.sessions
        WHERE id = :sessionId
    """.trimIndent()

    fun findUserByEmail(email: String): UserAuthRow? {
        return jdbi.withHandle<UserAuthRow?, Exception> { handle ->
            handle.createQuery(findUserByEmailSql)
                .bind("email", email.lowercase())
                .map { rs, _ ->
                    UserAuthRow(
                        id = rs.getObject("id", UUID::class.java),
                        email = rs.getString("email"),
                        passwordHash = rs.getString("password_hash"),
                    )
                }
                .findOne()
                .orElse(null)
        }
    }

    /**
     * Inserts a new session row and returns the UUIDv7 generated by Postgres.
     */
    fun startNewSession(userId: UUID): UUID {
        return jdbi.withHandle<UUID, Exception> { handle ->
            handle.createQuery(startNewSessionSql)
                .bind("userId", userId)
                .mapTo(UUID::class.java)
                .one()
        }
    }

    /**
     * Validates a session and returns the associated user if it's still valid.
     */
    fun getSessionUser(sessionId: UUID): SessionUser? {
        return jdbi.withHandle<SessionUser?, Exception> { handle ->
            handle.createQuery(getSessionUserSql)
                .bind("sessionId", sessionId)
                .map { rs, _ ->
                    SessionUser(
                        userId = rs.getObject("user_id", UUID::class.java),
                        email = rs.getString("email"),
                    )
                }
                .findOne()
                .orElse(null)
        }
    }

    /**
     * Deletes a session (for logout).
     */
    fun deleteSession(sessionId: UUID) {
        jdbi.withHandle<Int, Exception> { handle ->
            handle.createUpdate(deleteSessionSql)
                .bind("sessionId", sessionId)
                .execute()
        }
    }
}
